apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-actions-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: gh-actions-runners-infra
  source:
    repoURL: git@github.com:jvizueta/k8s-manifests-private.git
    targetRevision: main
    path: gh-actions-runners/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
       - CreateNamespace=true
