apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: dev
  source:
    repoURL: git@github.com:jvizueta/k8s-manifests-public.git
    targetRevision: main
    path: ai-customer-service/counter-agent/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-customer-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true