apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.5.2   # Use the latest stable version
    helm:
      values: |
        auth:
          enabled: false     # For development; set to true for production
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-customer-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true