apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  project: dev            # or "default" if you don't have an AppProject called "dev"
  source:
    repoURL: git@github.com:jvizueta/k8s-manifests-public.git
    targetRevision: main
    path: nginx
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true