apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-groundhog2k
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://groundhog2k.github.io/helm-charts/
    chart: redis
    targetRevision: 2.1.4   # Set a specific version or a semver range
    helm:
      values: |
        # --- Basic configuration ---
        replica:
          enabled: false          # Single instance (true = enable replication)
        service:
          type: ClusterIP         # Use ClusterIP unless you need external access
          port: 6379
        persistence:
          enabled: true           # Enable persistence for data durability
          accessModes: ["ReadWriteOnce"]
          size: 8Gi
          storageClass: "local-path"        # Set your storage class (e.g. "longhorn", "local-path", etc.)

        # --- Resource requests/limits ---
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        # --- Health checks ---
        livenessProbe:
          enabled: true
        readinessProbe:
          enabled: true

        # Note: By default, the chart deploys Redis without authentication.
        # To enable password protection, configure:
        # auth:
        #   enabled: true
        #   password: <your-password-here>
        # Or reference an existing secret:
        #   existingSecret: redis-auth
        #   existingSecretKey: redis-password

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-customer-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
