apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repositories
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"   # instala ANTES do ARC
spec:
  project: core
  source:
    repoURL: git@github.com:jvizueta/k8s-manifests-private.git
    targetRevision: main
    path: argocd-repositories
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
