apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lyra-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: dev
  source:
    repoURL: git@github.com:jvizueta/lyra.git
    targetRevision: main
    path: k8s/lyra/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: lyra-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true