apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-dev
  namespace: argocd
spec:
  project: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-dev
  sources:
    # 1) Overlay Kustomize: aplica o Secret primeiro (wave -1)
    - repoURL: git@github.com:jvizueta/k8s-manifests-private.git
      targetRevision: main
      path: mysql/overlays/dev
      ref: values
      kustomize: {}   # sem buildOptions aqui

    # 2) Helm do Bitnami usando o values.yaml do overlay
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mysql
      targetRevision: 14.0.3
      helm:
        releaseName: mysql
        valueFiles:
          - $values/mysql/overlays/dev/values.yaml

    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.2
      helm:
        releaseName: mysql-ingress
        valueFiles:
          - $values/mysql/overlays/dev/ingress-nginx-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
