apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  source:
    repoURL: git@github.com:jvizueta/k8s-manifests-public.git
    targetRevision: main
    path: cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true